### ISSUE TITLE
Roadmap 2.x

### ISSUE THREAD

**Issue by albertosantini** [albertosantini/node-rio#20]
Please, comment this issue about RFP (Request for Proposal) for rio 2.x.

**Status - 15 nov 2015** - merged

- [X] Unify the interface API with `evaluate(params)` - (#22 mandatory task).
- [X] Split the source code - (#23 mandatory task).
- [ ] Support reusable connections (sessions) - (#21 new feature).
- [ ] Support crypted authentication - (new feature).
- [ ] Browserify distribution - (new optional feature).
- [ ] Use debug package (vs. custom logging) - (internal change).

(Don't forget any implementation needs to work in Linux and Windows box).

**Comment by albertosantini** [comment]
Just an update.

In the last few months I have been developing [Argo](https://github.com/albertosantini/argo), a trading platform to develop realtime strategies. 

That project might be a good use case to test `rio` and finally to create change requests for 2.x.
I did not forget rio. :)

**Comment by albertosantini** [comment]
Add debug package task.

**Comment by satyashani** [comment]
Proposals -
1. The error passed to evaluate function is currently either a string or boolean true. I think it should be the Error("Error String") object which is more standard across nodejs.
2. I cannot get rio to parse json response(I get SEXP type = 162). I think JSON should be supported.
I've made these updates in my branch satyashani/node-rio@9c9eb8f.

**Comment by albertosantini** [comment]
@satyashani 
- Any link to Node.js doc (or blog post about handling error) about 1)?
- What is your use case about 2) and where is the Rserve doc about type 162?

**Comment by satyashani** [comment]
@albertosantini 
For error handling -
   https://docs.nodejitsu.com/articles/errors/what-are-the-error-conventions 
   http://stackoverflow.com/questions/7310521/node-js-best-practice-exception-handling
For type 162 I didn't find anything in docs(https://rforge.net/Rserve/dev.html) , I don't work with R but have to connect to an instance. My proposal is based on what I found when I set enableDebug(true). The error was -
Type 162 is currently not implemented

**Comment by albertosantini** [comment]
Hey @satyashani.

I think there is a misunderstanding. The binary protocol of Rserve, implemented in rio, can transfer, for instance, strings, but it doesn't exist a json type. Indeed you cannot find any documentation. 

In rio examples I have been using `RJSONIO` package.
Notice the final result it is a string.

This is R console transcript:
```
> require(RJSONIO)
Loading required package: RJSONIO
> jsonstr="{\"result\":{\"key1\":[1],\"key2\":[true]}}"
> fromJSON(jsonstr)
$result
$result$key1
[1] 1

$result$key2
[1] TRUE


> toJSON(fromJSON(jsonstr))
[1] "{\n \"result\": {\n \"key1\":      1,\n\"key2\": true \n} \n}"
> 
```

Now I execute the same commands using `jsonlite` package.
```
> require(jsonlite)
Loading required package: jsonlite

Attaching package: ‘jsonlite’

The following object is masked from ‘package:utils’:

    View

> jsonstr="{\"result\":{\"key1\":[1],\"key2\":[true]}}"
>  fromJSON(jsonstr)
$result
$result$key1
[1] 1

$result$key2
[1] TRUE


>  toJSON(fromJSON(jsonstr))
{"result":{"key1":[1],"key2":[true]}} 
> class(toJSON(fromJSON(jsonstr)))
[1] "json"
> 
```

You can notice the latest result is not a string, it is an R object, a class, and you need to serialize it.
We cannot parse every object or class.

To pass json objects between R world and Node.js one, you can give a look at the examples `ex3.js` and `ex3.R`.

About the error handling I like this doc, confirming the best practice:
https://www.joyent.com/developers/node/design/errors

`callback(new Error('something bad happened'));`

However I gave a look at mainstream project and there is not a consensus about the object type of `err` (string or Error object) in the callback. Generally speaking, I am not against it.

Other users may give their feedback about it.

**Comment by satyashani** [comment]
I'd rather ask my colleagues to use ```RJSONIO```. I don't understand why S expression type is 162 when it is not implemented at all in ```Rserve```. Thanks for your time on this.

**Comment by albertosantini** [comment]
`rio 1.4.0` is a solid version.

I will merge `dev-2.x` branch in the master in a few weeks, creating `2.0.0` release.

I know some features have not been implemented, but, I think, it is worthy moving on and looking forward.

Thanks for the patience.

**Comment by g2010a** [comment]
Thank you for all the hard work; a feature that would be great to implement is encrypted authentication... R is single-threaded and not nice to other processes, so I've found it better to run it remotely on its own server -- you might eventually have to do that with Argo as well -- but plaintext authentication is a security problem.

**Comment by albertosantini** [comment]
At last merged. Polishing details in the next weeks and then publishing 2.0.0.

If anyone is interested to any 2.x point not implemented, please open a new issue.
Contributing is welcome. :)
